[phases.setup]
nixPkgs = ["python312", "poetry", "gcc", "glibc", "gcc.cc.lib"]

[phases.install]
cmds = ["cd backend && poetry install"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"

